apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: sdp-app
  template:
    metadata:
      labels:
        app: sdp-app
    spec:
      containers:
        - name: sdp-app
          image: zull123/dtl-dp:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sdp-app
spec:
  selector:
    app: sdp-app
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
